/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BANCO_H_RPCGEN
#define _BANCO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct conta {
	int id;
	float saldo;
};
typedef struct conta conta;

struct transacao {
	int id;
	float saldo;
};
typedef struct transacao transacao;

struct token {
	int conta_id;
	int token;
};
typedef struct token token;

#define BANCO_PROG 0x12345000
#define BANCO_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define abreConta 1
extern  int * abreconta_1(int *, CLIENT *);
extern  int * abreconta_1_svc(int *, struct svc_req *);
#define fechaConta 2
extern  int * fechaconta_1(int *, CLIENT *);
extern  int * fechaconta_1_svc(int *, struct svc_req *);
#define authConta 3
extern  int * authconta_1(int *, CLIENT *);
extern  int * authconta_1_svc(int *, struct svc_req *);
#define deposito 4
extern  int * deposito_1(transacao *, CLIENT *);
extern  int * deposito_1_svc(transacao *, struct svc_req *);
#define saque 5
extern  int * saque_1(transacao *, CLIENT *);
extern  int * saque_1_svc(transacao *, struct svc_req *);
#define retornaSaldo 6
extern  float * retornasaldo_1(int *, CLIENT *);
extern  float * retornasaldo_1_svc(int *, struct svc_req *);
#define checkSenha 7
extern  int * checksenha_1(token *, CLIENT *);
extern  int * checksenha_1_svc(token *, struct svc_req *);
#define geraSenha 8
extern  int * gerasenha_1(token *, CLIENT *);
extern  int * gerasenha_1_svc(token *, struct svc_req *);
#define falhaSenha 9
extern  int * falhasenha_1(token *, CLIENT *);
extern  int * falhasenha_1_svc(token *, struct svc_req *);
extern int banco_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define abreConta 1
extern  int * abreconta_1();
extern  int * abreconta_1_svc();
#define fechaConta 2
extern  int * fechaconta_1();
extern  int * fechaconta_1_svc();
#define authConta 3
extern  int * authconta_1();
extern  int * authconta_1_svc();
#define deposito 4
extern  int * deposito_1();
extern  int * deposito_1_svc();
#define saque 5
extern  int * saque_1();
extern  int * saque_1_svc();
#define retornaSaldo 6
extern  float * retornasaldo_1();
extern  float * retornasaldo_1_svc();
#define checkSenha 7
extern  int * checksenha_1();
extern  int * checksenha_1_svc();
#define geraSenha 8
extern  int * gerasenha_1();
extern  int * gerasenha_1_svc();
#define falhaSenha 9
extern  int * falhasenha_1();
extern  int * falhasenha_1_svc();
extern int banco_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_conta (XDR *, conta*);
extern  bool_t xdr_transacao (XDR *, transacao*);
extern  bool_t xdr_token (XDR *, token*);

#else /* K&R C */
extern bool_t xdr_conta ();
extern bool_t xdr_transacao ();
extern bool_t xdr_token ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BANCO_H_RPCGEN */
