/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "banco.h"

bool_t
xdr_conta (XDR *xdrs, conta *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->saldo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_transacao (XDR *xdrs, transacao *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->saldo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_token (XDR *xdrs, token *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->conta_id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->token))
		 return FALSE;
	return TRUE;
}
