/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "banco.h"
#include <stdio.h>

#define NUM_CONTA 100

conta contas[NUM_CONTA];
token tokenContas[NUM_CONTA];

int erroglobal = 0;
int valorglobal = 0;
int idglobal = 0;

int verificaContaBD(int _id)
{
	for (int i = 0; i < NUM_CONTA; i++)
	{
		if (contas[i].id == _id)
		{
			return _id;
		}
	}

	return -1;
}

int *abreconta_1_svc(int *argp, struct svc_req *rqstp)
{
	static int result;
	int id = *argp;

	if (verificaContaBD(id) == -1)
	{
		contas[id].id = id;
		contas[id].saldo = 0.0;
		result = id;
	}
	else
	{

		result = -1;
	}

	return &result;
}

int *fechaconta_1_svc(int *argp, struct svc_req *rqstp)
{
	static int result;
	int id = *argp;

	if (verificaContaBD(id) != -1)
	{
		contas[id].id = 999;
		contas[id].saldo = 999;
		result = 0;
	}
	else
	{
		result = -1;
	}

	return &result;
}

int *authconta_1_svc(int *argp, struct svc_req *rqstp)
{
	static int result;
	int id = *argp;

	result = verificaContaBD(id);

	return &result;
}

int *deposito_1_svc(transacao *argp, struct svc_req *rqstp)
{
	static int result;
	int id = argp->id;
	float valor = argp->saldo;

	result = -1;
	if (verificaContaBD(id) != -1)
	{
		contas[id].saldo = contas[id].saldo + valor;
		result = 0;
	}

	return &result;
}

int *saque_1_svc(transacao *argp, struct svc_req *rqstp)
{
	static int result;
	int id = argp->id;
	int valor = argp->saldo;
	int erro = argp->erro;

	result = -1;
	if (verificaContaBD(id) != -1)
	{	
		if(erro == 1 && erroglobal == 1 && valorglobal != valor) erroglobal = 0;

		if(erro == 1 && erroglobal == 0) 
		{	
			contas[id].saldo = contas[id].saldo - valor;
			result = 2;
			erroglobal = 1;
			idglobal = id;
			valorglobal = valor;
		} 
		else if(erro == 1 && erroglobal == 1 && idglobal == id && valorglobal == valor) 
		{	
			result = 3;
			erroglobal = 0;
		}
		else
		{
			contas[id].saldo = contas[id].saldo - valor;
			result = 0;
		}

	}

	return &result;
}

float *
retornasaldo_1_svc(int *argp, struct svc_req *rqstp)
{
	static float result;
	int id = *argp;

	result = -1.0;
	if (verificaContaBD(id) != -1)
	{
		result = contas[id].saldo;
	}

	return &result;
}

int *checksenha_1_svc(token *argp, struct svc_req *rqstp)
{
	static int result;
	int id = argp->conta_id;
	int token = argp->token;

	if (token == 0) //primeira senha
	{
		tokenContas[id].conta_id = id;
		tokenContas[id].token = 0;
		result = 0;
	}
	else if (tokenContas[id].token == token) //senha correta
	{
		result = 0;
	}
	else //senha sem atualizacoes
	{
		result = -1;
	}

	return &result;
}

int *gerasenha_1_svc(token *argp, struct svc_req *rqstp)
{
	static int result;
	int contaId = argp->conta_id;

	if (verificaContaBD(contaId) != -1)
	{
		tokenContas[contaId].token = tokenContas[contaId].token + 2;
		result = tokenContas[contaId].token;
	}
	else
	{
		result = -1;
	}
	return &result;
}
